### ISSUE TITLE
not able to instal?

### ISSUE THREAD

**Issue by MSandro** [tengattack/certbot-dns-aliyun#4]
I am using Centos 7.6 and Python 2.7.5 and I think something goes wrong ...
```
-bash: virtualenv: command not found
[clusteradmin@LBR certbot-dns-aliyun]$ python --version
Python 2.7.5
[clusteradmin@LBR certbot-dns-aliyun]$ sudo python setup.py install
/usr/lib64/python2.7/distutils/dist.py:267: UserWarning: Unknown distribution option: 'python_requires'
  warnings.warn(msg)
running install
running bdist_egg
running egg_info
writing requirements to certbot_dns_aliyun.egg-info/requires.txt
writing certbot_dns_aliyun.egg-info/PKG-INFO
writing top-level names to certbot_dns_aliyun.egg-info/top_level.txt
writing dependency_links to certbot_dns_aliyun.egg-info/dependency_links.txt
writing entry points to certbot_dns_aliyun.egg-info/entry_points.txt
reading manifest file 'certbot_dns_aliyun.egg-info/SOURCES.txt'
reading manifest template 'MANIFEST.in'
warning: no files found matching 'README.rst'
writing manifest file 'certbot_dns_aliyun.egg-info/SOURCES.txt'
installing library code to build/bdist.linux-x86_64/egg
running install_lib
running build_py
creating build/bdist.linux-x86_64/egg
creating build/bdist.linux-x86_64/egg/certbot_dns_aliyun
copying build/lib/certbot_dns_aliyun/dns_aliyun_test.py -> build/bdist.linux-x86_64/egg/certbot_dns_aliyun
copying build/lib/certbot_dns_aliyun/__init__.py -> build/bdist.linux-x86_64/egg/certbot_dns_aliyun
copying build/lib/certbot_dns_aliyun/alidns_test.py -> build/bdist.linux-x86_64/egg/certbot_dns_aliyun
copying build/lib/certbot_dns_aliyun/dns_aliyun.py -> build/bdist.linux-x86_64/egg/certbot_dns_aliyun
copying build/lib/certbot_dns_aliyun/alidns.py -> build/bdist.linux-x86_64/egg/certbot_dns_aliyun
byte-compiling build/bdist.linux-x86_64/egg/certbot_dns_aliyun/dns_aliyun_test.py to dns_aliyun_test.pyc
byte-compiling build/bdist.linux-x86_64/egg/certbot_dns_aliyun/__init__.py to __init__.pyc
byte-compiling build/bdist.linux-x86_64/egg/certbot_dns_aliyun/alidns_test.py to alidns_test.pyc
byte-compiling build/bdist.linux-x86_64/egg/certbot_dns_aliyun/dns_aliyun.py to dns_aliyun.pyc
byte-compiling build/bdist.linux-x86_64/egg/certbot_dns_aliyun/alidns.py to alidns.pyc
creating build/bdist.linux-x86_64/egg/EGG-INFO
copying certbot_dns_aliyun.egg-info/PKG-INFO -> build/bdist.linux-x86_64/egg/EGG-INFO
copying certbot_dns_aliyun.egg-info/SOURCES.txt -> build/bdist.linux-x86_64/egg/EGG-INFO
copying certbot_dns_aliyun.egg-info/dependency_links.txt -> build/bdist.linux-x86_64/egg/EGG-INFO
copying certbot_dns_aliyun.egg-info/entry_points.txt -> build/bdist.linux-x86_64/egg/EGG-INFO
copying certbot_dns_aliyun.egg-info/requires.txt -> build/bdist.linux-x86_64/egg/EGG-INFO
copying certbot_dns_aliyun.egg-info/top_level.txt -> build/bdist.linux-x86_64/egg/EGG-INFO
zip_safe flag not set; analyzing archive contents...
creating 'dist/certbot_dns_aliyun-0.23.0.dev0-py2.7.egg' and adding 'build/bdist.linux-x86_64/egg' to it
removing 'build/bdist.linux-x86_64/egg' (and everything under it)
Processing certbot_dns_aliyun-0.23.0.dev0-py2.7.egg
Removing /usr/lib/python2.7/site-packages/certbot_dns_aliyun-0.23.0.dev0-py2.7.egg
Copying certbot_dns_aliyun-0.23.0.dev0-py2.7.egg to /usr/lib/python2.7/site-packages
certbot-dns-aliyun 0.23.0.dev0 is already the active version in easy-install.pth

Installed /usr/lib/python2.7/site-packages/certbot_dns_aliyun-0.23.0.dev0-py2.7.egg
Processing dependencies for certbot-dns-aliyun==0.23.0.dev0
Traceback (most recent call last):
  File "setup.py", line 66, in <module>
    test_suite='certbot_dns_aliyun',
  File "/usr/lib64/python2.7/distutils/core.py", line 152, in setup
    dist.run_commands()
  File "/usr/lib64/python2.7/distutils/dist.py", line 953, in run_commands
    self.run_command(cmd)
  File "/usr/lib64/python2.7/distutils/dist.py", line 972, in run_command
    cmd_obj.run()
  File "/usr/lib/python2.7/site-packages/setuptools/command/install.py", line 73, in run
    self.do_egg_install()
  File "/usr/lib/python2.7/site-packages/setuptools/command/install.py", line 101, in do_egg_install
    cmd.run()
  File "/usr/lib/python2.7/site-packages/setuptools/command/easy_install.py", line 380, in run
    self.easy_install(spec, not self.no_deps)
  File "/usr/lib/python2.7/site-packages/setuptools/command/easy_install.py", line 604, in easy_install
    return self.install_item(None, spec, tmpdir, deps, True)
  File "/usr/lib/python2.7/site-packages/setuptools/command/easy_install.py", line 655, in install_item
    self.process_distribution(spec, dist, deps)
  File "/usr/lib/python2.7/site-packages/setuptools/command/easy_install.py", line 706, in process_distribution
    [requirement], self.local_index, self.easy_install
  File "/usr/lib/python2.7/site-packages/pkg_resources.py", line 631, in resolve
    requirements.extend(dist.requires(req.extras)[::-1])
  File "/usr/lib/python2.7/site-packages/pkg_resources.py", line 2497, in requires
    "%s has no such extra feature %r" % (self, ext)
pkg_resources.UnknownExtra: requests 2.6.0 has no such extra feature 'security'
```

**Comment by tengattack** [comment]
Could you run `certbot --nginx` and have a try? Is there have same error?

**Comment by tengattack** [comment]
BTW, how did you install the certbot?

And try to upgrade `acme` package:
```sh
pip install acme --upgrade
```
