### ISSUE TITLE
阿里云dns不行？？？

### ISSUE THREAD

**Issue by chenyu1990** [tengattack/certbot-dns-aliyun#6]
certbot -a certbot-dns-aliyun:dns-aliyun -i nginx -d xxxx.com -d "*.xxxx.com" --server https://acme-v02.api.lets
encrypt.org/directory --certbot-dns-aliyun:dns-aliyun-credentials  ~/.secerts/certbot/aliyun

Encountered exception during recovery:
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/certbot/error_handler.py", line 124, in _call_registered
    self.funcs[-1]()
  File "/usr/local/lib/python2.7/dist-packages/certbot/auth_handler.py", line 220, in _cleanup_challenges
    self.auth.cleanup(achalls)
  File "/usr/local/lib/python2.7/dist-packages/certbot/plugins/dns_common.py", line 77, in cleanup
    self._cleanup(domain, validation_domain_name, validation)
  File "/usr/local/lib/python2.7/dist-packages/certbot_dns_aliyun/dns_aliyun.py", line 53, in _cleanup
    self._get_alidns_client().del_txt_record(domain, validation_name, validation)
  File "/usr/local/lib/python2.7/dist-packages/certbot_dns_aliyun/alidns.py", line 81, in del_txt_record
    domain = self._find_domain_id(domain)
  File "/usr/local/lib/python2.7/dist-packages/certbot_dns_aliyun/alidns.py", line 54, in _find_domain_id
    .format(domain, domain_name_guesses))
PluginError: Unable to determine zone identifier for xxxx.com using zone names: [u'xxxx.com', u'com']

**Comment by tengattack** [comment]
aliyun 的 RAM 子账号是对的吗？DNS 列表上有多页域名吗？
